import Head from 'next/head'

export default function NormalHeader () {
    return (
        <Head>
            <title>StoreCart</title>
            <meta name="description" content="Generated by StoreCart" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}